{{- if .Values.apptoml.enabled }}
{{- range .Values.apptoml.mount }}
apiVersion: v1
kind: ConfigMap 
metadata:
  name: {{ $.Values.deployment.projectName }}-{{ .configName }}
  namespace: {{ $.Values.deployment.namespace }}
data:
  {{ .filename }}: | {{ range $.Files.Lines .filename }}
    {{ . }}{{ end }}     
---
{{- end }}
{{- end }}