apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.projectName }}
  namespace: {{ .Values.deployment.namespace }}
  labels:
    app: {{ .Values.deployment.projectName }}
    addToHostAliases: "true"
spec:
  type: {{.Values.svc.clustertype}}
  ports:
  {{- range .Values.deployment.port }}
  - port: {{ . }}
    name: port-{{ . }}
    targetPort: {{ . }}
    protocol: TCP
  {{- end }}
  selector:
    app: {{ .Values.deployment.projectName }}
