name: Cosmos Build
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Evmos release version to build docker image'
        required: true


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag, and push image to Dockerhub
        env:
          IMAGE_TAG: ${{ github.event.inputs.version }}
        run: |
          docker build -t ayushvv/evmos:$IMAGE_TAG --build-arg VERSION=$IMAGE_TAG .
          docker push ayushvv/evmos:$IMAGE_TAG
